### ISSUE TITLE
Imports issue with lib beta 8 and Angular 7

### ISSUE THREAD

**Issue by sebaherrera** [cyrilletuzi/angular-async-local-storage#103]
Hi. Since v8 beta 8, there is a ¿charset issue? which alters some imports and makes full library to fail. For example:

![1111](https://user-images.githubusercontent.com/44304528/57552601-cadc9400-7342-11e9-8e0b-b23d3daa3204.PNG)

On build process, there are lots of warnings:

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 267:36-54
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 714:40-58
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 869:43-61
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 947:37-55
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 1001:36-54
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 1143:33-51
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 1281:35-53
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 714:138-146
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 714:161-169
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 714:187-195
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 869:147-155
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 869:168-176
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 1001:129-137
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 1001:152-160
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 1001:173-181
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 1001:196-204
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 1001:222-230
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 1143:117-125
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 1143:142-150
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 1143:167-175
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 1143:188-196
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js 1281:123-131
"export 'ɵɵinject' was not found in '@angular/core'

And here is my setup:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.9
Node: 11.9.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@angular/pwa                      0.13.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0

Note that downgrading to beta 7 makes it work again and reinstalling beta 8-10 reinstates the error.

**Comment by cyrilletuzi** [comment]
Thanks for testing the beta.

I'm aware of the issue, it's an issue on the Angular side (but it's not a charset issue). I was waiting for more RC from Angular to see if the problem is solved. So I'll do an update soon with the last RC. If the problem is still here, it will need an issue on the Angular repo.

**Comment by cyrilletuzi** [comment]
For information, despite the warnings, is your app working as expected?

**Comment by cyrilletuzi** [comment]
Released beta.11. Unfortunately the issue is still there with last Angular RC.

**Comment by cyrilletuzi** [comment]
Note: seems similar to angular/angular#27251

**Comment by sebaherrera** [comment]
> For information, despite the warnings, is your app working as expected?

Parts related to the library don't work at all, but the rest of the app is working right, since it's just production code plus latest beta version of the library.

**Comment by cyrilletuzi** [comment]
Results from investigation:
- works in Angular 8, the issue is only when using v8 of the lib on Angular 7,
- it worked until Angular 8 beta.11, breaks since Angular 8  beta.12, which is also the version where Angular bumped from TS 3.3 to 3.4.

**Comment by cyrilletuzi** [comment]
Issue opened in Angular repo.

**Comment by sebaherrera** [comment]
Interesting to see that Angular is at Release Candidate stage....

Thanks for your help and the followup.

**Comment by cyrilletuzi** [comment]
Following the response of Angular team in angular/angular#27251, v8 of this lib will only support Angular 8. Thanks for reporting.
