### ISSUE TITLE
Security exception when cookies are fully blocked

### ISSUE THREAD

**Issue by AstRonin** [cyrilletuzi/angular-async-local-storage#118]
I looked on documentation but not found an answer.
How will behave this library when the cookies disabled?
In generally, for native localStorage In Chrome we can see such error:
`DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.` In Edge it looks `SCRIPT5022: SecurityError`.
Will your library switch to some *In Memory* storage or just say "I cannot work" and show error?

Thanks

**Comment by cyrilletuzi** [comment]
As a general answser, this lib try to check the availability of the different APIs, to fallback to another API when necessary. It goes like this:
- try `indexedDB`
- if not possible, try `localStorage`
- if not possible, try in memory storage

As a more specific answser, there are already many API availability checks, but it's not impossible that some edgy cases are not yet managed.

But if it's the case, a detailed report would be needed to take action. Currently I'm quite puzzled with your question, as I don't see the link between cookies and `localStorage`.

**Comment by AstRonin** [comment]
I did not see also, before my client disable cookies and said me what a site did not loading...
You can try, it is easy, just switch off as I highlighted on printscreen:
![image](https://user-images.githubusercontent.com/2378239/58952741-9b844000-87a5-11e9-8326-1e287950340c.png)
(Second for iframe)

By the way, thanks for your answer, very good.

**Comment by cyrilletuzi** [comment]
Indeed, you're right. Fixed via #119, released in v8.0.1.

Thanks for reporting. 👍

**Comment by AstRonin** [comment]
thanks, but can you this work for 6 version also? I use Angular 7 and you recommended use 6 version...

**Comment by cyrilletuzi** [comment]
Released in v6.2.4.

**Comment by AstRonin** [comment]
I updated to 6.2.4

in modules I see your changes:
![image](https://user-images.githubusercontent.com/2378239/58996278-88ef2280-8808-11e9-8aa8-0b7f2afaf588.png)

but I see this error:
![image](https://user-images.githubusercontent.com/2378239/58996155-0bc3ad80-8808-11e9-953f-60107e951d7b.png)

As I understand these changes not enough, when library try open indexedDB this catch error and set:
`this.fallback = new LocalStorageDatabase(prefix);` and again try use native localStorage...

So... indexedDB can be in window but cannot open through cookies block...

**Comment by cyrilletuzi** [comment]
I've reopened the issue.

But I won't be able to take care of this now, expect a fix in 2 weeks.

**Comment by cyrilletuzi** [comment]
Fix released in 8.0.2 and 6.0.5.
