### ISSUE TITLE
Library and Demo not working in Edge or IE11

### ISSUE THREAD

**Issue by palmtreefrb** [cyrilletuzi/angular-async-local-storage#13]
The demo works correctly in Chrome. Get the following error in Edge/IE11
File: localhost:3000
ERROR Error: IndexedDB connection issue.
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "IndexedDB connection issue.",
      message: "IndexedDB connection issue.",
      name: "Error",
      stack: "Error: IndexedDB connection issue.
   at SafeSubscriber.prototype.error (eval code:207:17)
   at Subscriber.prototype._error (eval code:128:9)
   at Subscriber.prototype.error (eval code:102:13)
   at Subscriber.prototype._error (eval code:128:9)
   at Subscriber.prototype.error (eval code:102:13)
   at OuterSubscriber.prototype.notifyError (eval code:22:9)
   at InnerSubscriber.prototype._error (eval code:26:9)
   at Subscriber.prototype.error (eval code:102:13)
   at OuterSubscriber.prototype.notifyError (eval code:22:9)
   at InnerSubscriber.prototype._error (eval code:26:9)"
   }
![image](https://user-images.githubusercontent.com/7799495/32851215-39755d70-c9e9-11e7-9851-c8584d7bdb81.png)

**Comment by cyrilletuzi** [comment]
I'm having a hard time to test in IE11 because of a configuration problems, but in Edge I can already say tests work perfectly.

The contrary would have been surprising as the library is not new and such a big issue would have been reported before.

Problem with IE and Edge is that they can be modified in enterprise to block some features, typically like IndexedDB. And in that case I can't help at all. Are you sure your IE/Edge is a normally configured one ?

**Comment by cyrilletuzi** [comment]
First thing to check is your X-UA-Compatible mode.

**Comment by cyrilletuzi** [comment]
I've updated master for testing : there was a missing systemjs config in app demo, and I added Edge/IE testing tools. You just have to (un)comment the good `browsers` line at the end of `karma.conf.js`.

So Edge and IE11 demo and tests are working.

But for information, IndexedDB was missing in my IE11 on Windows 10. I had to completely reinitialize its settings to make it work. So definitively IE configuration is messing all of this, but the lib can do nothing about it.

**Comment by palmtreefrb** [comment]
Hmmm, well I tested IndexedDb on the same IE11 browser that your library is throwing the error. I will continue to debug see if I can find anything. Thanks for looking at it.

**Comment by cyrilletuzi** [comment]
Closing as there are no evidence of a problem in the library, feel free to post any further information you may find (including ones not relative to the library, like restrictions on your network, would be useful to know).

**Comment by cyrilletuzi** [comment]
For info : last release (3.1.1) includes browser info when errors happen. Could you share the results of your debug (what was the problem if it's already solved, or what is the more precise error message with the new version of the lib) ?
