### ISSUE TITLE
IndexedDB connection issue in Electron

### ISSUE THREAD

**Issue by Pato91** [cyrilletuzi/angular-async-local-storage#20]
I'm using angular  + electron to whip up some app. When I try to access the items I placed in to this store, I get the error;
ERROR Error: IndexedDB connection issue.
    at MergeMapSubscriber.eval [as project] (angular-async-local-storage.es5.js:301)
    at MergeMapSubscriber._tryNext (mergeMap.js:128)
    at MergeMapSubscriber._next (mergeMap.js:118)
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:91)
    at IDBOpenDBRequest.handler (FromEventObservable.js:212)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4617)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at ZoneTask.invokeTask [as invoke] (zone.js:499)

How can I work that out to get the module work because I don't know if its just because I'm using electron or not!

Thanks

**Comment by cyrilletuzi** [comment]
I never used Electron myself, but a quick look on Google shows IndexedDB is supported by Electron, as it's just the Chrome engine, so this lib should work, except if there is some special config to do in Electron to enable it.

I'll investigate this.

**Comment by Pato91** [comment]
Thank you! Let me also look at whether there are any special configs for electron. But, I would like for this issue to stay open for a while longer to see if the community has some ideas about this or has used the module in an Electron env.

**Comment by hannesrohde** [comment]
Strange, I'm having the same issue under Firefox 57.0.2:

We are using version 4.4.6 of Angular and 2.0.1 of angular-async-local-storage and our app fails to connect to the indexed db with the same stack trace:

message: "IndexedDB connection issue."
stack:
IndexedDBDatabase.prototype.toErrorObservable/<@webpack-internal:///../../../../angular-async-local-storage/angular-async-local-storage.es5.js:300:200
MergeMapSubscriber.prototype._tryNext@webpack-internal:///../../../../rxjs/_esm5/operators/mergeMap.js:133:22
MergeMapSubscriber.prototype._next@webpack-internal:///../../../../rxjs/_esm5/operators/mergeMap.js:123:13
Subscriber.prototype.next@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:96:13
FromEventObservable.prototype._subscribe/handler<@webpack-internal:///../../../../rxjs/_esm5/observable/FromEventObservable.js:218:35
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:425:17
onInvokeTask@webpack-internal:///../../../core/@angular/core.es5.js:4081:24
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:424:17
Zone.prototype.runTask@webpack-internal:///../../../../zone.js/dist/zone.js:192:28
ZoneTask.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:499:24
invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:1540:9
globalZoneAwareCallback@webpack-internal:///../../../../zone.js/dist/zone.js:1566:17

This seems to happen only on my machine, my colleague on a different OS with Firefox 57.0.1 can run it without problems.

Any idea how to fix/work around this?

**Comment by cyrilletuzi** [comment]
I don't think it's the same issue. This is a general error message if the connection to IndexedDB fails, which could be for several reasons. Can you open a different issue ? It could help other people when we'll find the problem.

But it's a good reminder that I should improve error messages in the lib (if this is possible). I'll plan that.

**Comment by hannesrohde** [comment]
Thanks for the quick reaction! I will try to find out what's wrong in my profile and depending on the outcome open a new issue with more information.

**Comment by cyrilletuzi** [comment]
I've tested with the official Electron quick starter and it works. So I'm closing this issue for now, feel free to add more information if you've found something special.

**Comment by cyrilletuzi** [comment]
For info : last release (3.1.1) includes browser info when errors happen. Could you share the results of your debug (what was the problem if it's already solved, or what is the more precise error message with the new version of the lib) ?

**Comment by elkozmon** [comment]
I get the same error in Firefox 57.0.4 when I'm in private window. I guess that's due to IndexedDB being disabled but it'd be nice if it could fallback to other storage method then.

**Comment by pinalbhatt** [comment]
Yes this does not work with browsers like IE, FF, Safari in an in-private mode as indexedDB is not support in such cases. And yes it would be nice if it could fall back to other storage methods then.

**Comment by cyrilletuzi** [comment]
This is not the same issue as the Electron one. Please continue the discussion (and help) in #26
