### ISSUE TITLE
Importing JSONSchema from another Ts file fails build

### ISSUE THREAD

**Issue by bogacg** [cyrilletuzi/angular-async-local-storage#200]
I'm exporting a function that generates my JSON schema from a TS file (with other type definitions) and import them in my Angular component.
Doing so fails the build, with error messages unrelated to `@ngx-pwa` library.

Defining same schema in component builds fine.

I'm using v9-beta1
Thanks

**Comment by cyrilletuzi** [comment]
Hi @bogacg, thanks for your interest for this lib. Could you provide a minimal reproduction of the issue so I can help you?

**Comment by bogacg** [comment]
I've made a minimal blank project to reproduce this issue and I did not get any errors. Apparently one of the libraries / Angular tech I'm using in my project don't play well `@ngx-pwa/local-storage`.
I'll try to add more libs I'm using in my main project till I see the same error and then share it with you.

**Comment by bogacg** [comment]
I'm closing this for the moment as testing all Angular modules & other libraries I'm using in my project is more time consuming than I've anticipated. I'll update here if new version of Angular gives a better error message or fixes it on its own.

**Comment by cyrilletuzi** [comment]
OK, thanks for the update.

From what you said, I think it's an issue on your build tools side. From this lib side, where the JSONSchema comes from has no consequence at all.
