### ISSUE TITLE
More config for change store name

### ISSUE THREAD

**Issue by ngocsangyem** [cyrilletuzi/angular-async-local-storage#219]
I have many users. And each user will have a single object store (table) with a single object store (table) name. The object store name will be generated by id + user name.

When I storing in indexedDb, a database name is `ngStorage` and object store name is `localStorage`. How can I change the object store name.

**Comment by cyrilletuzi** [comment]
Maybe read [the documentation](https://github.com/cyrilletuzi/angular-async-local-storage/blob/master/docs/COLLISION.md)?

Note that, even if I don't understand your use case (each user is a different client, so I don't see the need of having different store names), configuration of store names can only be done at initialization. So being as dynamic as you want may not be possible (as it's not sure you can do the code you need to get your user id and name at initialization). So it would be up to you to manage that by prefixing your indexes.
