### ISSUE TITLE
[8.2.3] Initial load fails with enabled --build-optimizer

### ISSUE THREAD

**Issue by bleuscyther** [cyrilletuzi/angular-async-local-storage#251]
When building the app in production mode (--build-otimizer , --aot) , 
datatabase is undefined.

For example  : 
```` javascript
// ngx-pwa-local-storage.js.pre-build-optimizer.js (from mapped)
...
   get(key, schema) {
        /* Get the data in storage */
        return this.database.get(key).pipe(
...

````
 **this.database** is undefined.

There is no error in the build logs.

it is possibly related to these:
https://github.com/angular/angular-cli/issues/13686 , https://github.com/manfredsteyer/angular-oauth2-oidc/issues/489

**Comment by cyrilletuzi** [comment]
Thanks for your feedback.

The lib is already configured to be in AOT everywhere, builds are run on each PR and of course my own projects are in AOT. It also works with Angular 9 which is in AOT by default.

So I'll need a reproduction of the issue to be able to help you.

**Comment by bleuscyther** [comment]
Ok i have been trying to do a repo.
I tried it on a blank IonicFramework it works, 
Also tried it on a another project it also works. 

I will add the dependencies one by one to see if nothing is  interfering.

**Comment by bleuscyther** [comment]
Found the issue, StorageMap was added in the providers list.
