### ISSUE TITLE
Private browsing issue in Firefox

### ISSUE THREAD

**Issue by cyrilletuzi** [cyrilletuzi/angular-async-local-storage#26]
Follow up of comments in #20 

`IndexedDB` is disabled in private ([Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=781982), [Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9968399/)). Same as pouchdb/pouchdb#5641

Same goes for [localStorage](https://gist.github.com/JohnAllsopp/1470989).

The lib should detect these cases and fallback to in-memory database.

Note it just has to avoid errors, local storage is useful for apps, where being in private browsing makes no sense.

Help is welcome for up to date information about browser support of `IndexedDB` and `localStorage` in private mode, and also for examples of detection for each case. Some seem trivial (like Edge), but some others seem quite difficult and may not be fixable (like Firefox).

**Comment by cyrilletuzi** [comment]
A first fix is released in 3.1.3 for browsers like Edge where `IndexedDB` is `undefined`.

I'll investigate the cases of browsers where the API are available but not functional. Not sure it will be possible to solve this.

**Comment by cyrilletuzi** [comment]
So, a summary of my tests in private mode : 

**indexedDB**
- OK in Chrome and Safari
- `null` in IE / Edge (not sure about Edge, maybe it's fixed)
- API available in Firefox but throwing error on `connect()`

**localStorage**
- didn't see any problem in any browser

**Solutions**

For IE/Edge, fallback to `localStorage` (fixed in 3.1.4).

For Firefox, it's an [open bug](https://bugzilla.mozilla.org/show_bug.cgi?id=781982) in the browser. It may be resolved soon, and I think this lib can't handle it in the current state. There is the same problem in all other libs managing local storage, and I didn't find any which resolved this issue.

I see only two solutions : 
- do async code in factory provider (not a good idea and probably not possible)
- switch the provider at runtime (not sure it's possible, and even if it is, it would too much complicate the lib code for just an edge case).

But if someone knows a good solution, fell free to comment.

**Comment by cyrilletuzi** [comment]
Following my request, the priority of the issue in Firefox bug tracker has been raised, so it may be fixed soon.

**Comment by cyrilletuzi** [comment]
For info, I tried to fix this issue inside the lib, but it seems impossible to do it in a right way. So we have to wait for Firefox to fix this.

**Comment by cyrilletuzi** [comment]
@elkozmon @pinalbhatt @hannesrohde I may have find a workaround for Firefox private browsing issue. Could you test with v6.1.0-beta.0?
`npm install @ngx-pwa/local-storage@6.1.0-beta.0`

**Comment by hannesrohde** [comment]
@cyrilletuzi I just tried it in our app and 6.1.0-beta.0 fixes the issue in Firefox private browsing!
(FWIW it also fixes an issue I observed just on my machine with Firefox in normal browsing mode)

Sorry for the late reply and thank you for having a look and fixing the issue!

**Comment by cyrilletuzi** [comment]
@hannesrohde Thanks for testing!

I need to investigate another related issue first, and then it will be released in stable.

**Comment by venoby** [comment]
Hi, I got v6.1.0-beta.0
On Firefox for ios works good.
Firefox in private mode on windows has next error:
**Invalid data in localStorage.**

String set in isFilerRelatedToUser not correct:
![image](https://user-images.githubusercontent.com/8698885/43837409-1739fca2-9b21-11e8-887c-4bfe292bc869.png)
![image 1](https://user-images.githubusercontent.com/8698885/43837411-18b6d276-9b21-11e8-90f0-c1ae9b68d2b9.png)

**Comment by cyrilletuzi** [comment]
@venoby Could you share the code relative to your issue? `Invalid data` error is when JSON parsing data retrieve from `localStorage` is wrong. Your example seems to show it has been previously stringified twice.

**Comment by cyrilletuzi** [comment]
@venoby Also, check with beta.1 first:
`npm install @ngx-pwa/local-storage@6.1.0-beta.1`

**Comment by venoby** [comment]
@cyrilletuzi Hi again, yep you are right. It was typo error in my code :see_no_evil:
6.1.0-beta.1 works fine in my app, thank you

**Comment by cyrilletuzi** [comment]
Fixed in 6.1.

**Comment by cyrilletuzi** [comment]
For information: after many years, this has finally been fixed in Firefox 115.
