### ISSUE TITLE
Error handling if there's error in data format

### ISSUE THREAD

**Issue by goss-gowtham** [cyrilletuzi/angular-async-local-storage#268]
There is no output emitter to throw an error, if there's an error in the format of data that we send and not fetchable through API. That is, if value is not integer and got in string, then there's no error thrown to identify it.

**Comment by cyrilletuzi** [comment]
I'm sorry but I don't understand what you describe. Could you share an example of the code you're talking about?

**Comment by goss-gowtham** [comment]
Sorry, this issue is with ngx-charts. Really sorry for wasting your time.
