### ISSUE TITLE
Moment saving

### ISSUE THREAD

**Issue by astra1** [cyrilletuzi/angular-async-local-storage#28]
I Know, I shall save Date type to "local storage", but i want to warn you about exception.
And thanks for very useful library!

![selection_212](https://user-images.githubusercontent.com/4422785/38920853-f3c4b90a-42fc-11e8-88cb-defa34ca25a8.png)

**Comment by cyrilletuzi** [comment]
Can you share the code resulting in this? Otherwise, I can't help with just the error.

**Comment by cyrilletuzi** [comment]
Closing for housekeeping purpose. Feel free to comment if you want to add the additional information required to look into this issue.
