### ISSUE TITLE
WARNING: No name was provided for external module in Angular 9

### ISSUE THREAD

**Issue by ochibooh** [cyrilletuzi/angular-async-local-storage#285]
Getting warning when building a library in Angular 9

`WARNING: No name was provided for external module '@ngx-pwa/local-storage' in output.globals – guessing 'localStorage'`

**Comment by ochibooh** [comment]
Fixed by adding `umdModuleIds` in `ng-package.json`

```json
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/my-lib",
  "lib": {
    "entryFile": "src/public-api.ts",
    "umdModuleIds": {
      "my-lib": "my-lib",
      "@ngx-pwa/local-storage": "@ngx-pwa/local-storage"
    }
  }
}
```

**Comment by cyrilletuzi** [comment]
Hi @ochibooh Thanks for your feedback.

While you found a workaround, this lib is strictly following Angular Package Format and is built with official Angular tooling (ie. CLI & ng-packagr). As it's just a warning, maybe it's not important (several warnings in ng-packagr build steps are false positives), but it doesn't seem right. So I encourage you to open an issue in [ng-packagr repo](https://github.com/ng-packagr/ng-packagr).
