### ISSUE TITLE
node_modules/@ngx-pwa/local-storage/local-storage has no exported member 'LocalStorageModule'.

### ISSUE THREAD

**Issue by whisher** [cyrilletuzi/angular-async-local-storage#33]
Hi there,
Sorry to bother you. 
I want to integrate your module
in my app but I've got
node_modules/@ngx-pwa/local-storage/local-storage has no exported member 'LocalStorageModule'.

npm install @ngx-pwa/local-storage@latest

```javascript
import { LocalStorageModule } from '@ngx-pwa/local-storage';
```

Can you help me, please?

Thanks in advance.

**Comment by cyrilletuzi** [comment]
From README:

> Then, for versions 4 & 5 only, include the LocalStorageModule in your app root module (just once, do NOT re-import it in your submodules). Since version 6, this step is no longer required and LocalStorageModule is removed.
