### ISSUE TITLE
ng build failed

### ISSUE THREAD

**Issue by kenken64** [cyrilletuzi/angular-async-local-storage#34]
src/app/app.module.ts(9,10): error TS2305: Module '"/home/kenneth/Projects/coinotc-wallet-api/wallet-mgmt-web/node_modules/@ngx-pwa/local-storage/local-storage"' has no exported member 'LocalStorageModule'.

**Comment by cyrilletuzi** [comment]
From README:

> Then, for versions 4 & 5 only, include the LocalStorageModule in your app root module (just once, do NOT re-import it in your submodules). Since version 6, this step is no longer required and LocalStorageModule is removed.
