### ISSUE TITLE
Observe is not working. 

### ISSUE THREAD

**Issue by AnkitMaheshwariIn** [cyrilletuzi/angular-async-local-storage#350]
When we set value and get it worked.

But when we change value the subscribe does not triggered and returns the updated value.
The below code console.log('locale', locale); does not print updated value after update.

this.localStorage.getItem('locale').subscribe((locale: string) => {
        console.log('locale', locale);
      }, () => {
        // Not called
      });

**Comment by cyrilletuzi** [comment]
From README:

> Note you'll only get one value: the Observable is here for asynchrony but is not meant to emit again when the stored data is changed. If you need to watch the value, version 9 introduced a watch() method, see the watching guide.

**Comment by AnkitMaheshwariIn** [comment]
To watch change detection. Any change in the code required after updating to Angular v9..?
