### ISSUE TITLE
How to watch change detection?

### ISSUE THREAD

**Issue by AnkitMaheshwariIn** [cyrilletuzi/angular-async-local-storage#351]
To watch change detection. Any change in the code required after updating to Angular v9..?

**Comment by cyrilletuzi** [comment]
I am sorry to tell that your behavior is not welcomed here:
- there is a [full documentation](https://github.com/cyrilletuzi/angular-async-local-storage/blob/master/docs/WATCHING.md) about what you need, and I already told you so in #350 
- this is not an issue but a support request
- posting the same question in another issue just 15 hours after the first one is called spamming

You are writing to a human being doing this library on his free time, not to a robot at your disposal.
