### ISSUE TITLE
 IndexedDB setter issue : Key already exists in the object store..

### ISSUE THREAD

**Issue by santanageorge** [cyrilletuzi/angular-async-local-storage#37]
IndexedDB setter issue : Key already exists in the object store..

first removing a item then iam adding item into local storage event hough it shows this error
i used this code

 this.localStorage.removeItem('selectedItem').subscribe(() => {
      this.localStorage.setItem('selectedItem', item).subscribe(() => { });
    }, (error) => {
      this.localStorage.setItem('selectedItem', item).subscribe(() => { });
    });

**Comment by cyrilletuzi** [comment]
Please provide a reproduction of the issue. This code is already tested in this lib with no problem, so more context is needed.

**Comment by cyrilletuzi** [comment]
Closing, as no more information was provided.

**Comment by cyrilletuzi** [comment]
For info, issue is being treated in #47

**Comment by cyrilletuzi** [comment]
Fixed in 6.1.1.
