### ISSUE TITLE
Does not work on Android (Chrome/Installed)

### ISSUE THREAD

**Issue by MunhozThiago** [cyrilletuzi/angular-async-local-storage#385]
Hi, I really did not find anything similar, so that's why I'm trying to ask for help here.

I used your lib for getting around with persistent storage in an angular pwa application. In the browser, it works like a charm and that's great, but whenever it comes to my cellphone, it crashes. I've tried to investigate whether it was on my side, but it seems that anything I try to persist or read data in the pwa app (on chrome or "installed") does really work.

Has anyone ever found some bug related to this? Maybe it could be related to browser capabilities or so, but since the support for android is "native" the db should have access to persist the data.

I'm really confused. 
Thanks for the great work!

**Comment by cyrilletuzi** [comment]
Hi, can you follow the issue template and provide a reproduction?

The lib works in all browsers scenarios.

**Comment by MunhozThiago** [comment]
Hi, @cyrilletuzi.
Sorry I did not have time to update the description yet. Indeed, I've found that the service-worker takes a lot of time to load and in the meantime, the service was trying to get/set local-storage and failed. It could be probably related to the life-cycle of the application. I'll try to investigate a little more and ping you back with an updated description.

**Comment by cyrilletuzi** [comment]
I'm using `@angular/service-worker` myself, and in the past I had some issues with the service worker init time too, but storage wasn't blocked. A quick search on Google also results in no results about restrictions on storage when using service workers. So except it's a browser bug in a new version, not sure it is the trail to follow.

**Comment by cyrilletuzi** [comment]
Closing this issue for house-keeping purpose. Feel free to comment and I'll reopen it.
