### ISSUE TITLE
.watch not firing in another tab

### ISSUE THREAD

**Issue by NejcCarl** [cyrilletuzi/angular-async-local-storage#386]
In one tab I am using set, delete and watch methods. All work fine. However if the same application is running in another tab, watch does not observe the changes. Is this intentional behavior or should I prepare a reproduction?

**Comment by cyrilletuzi** [comment]
This is the intended behavior, both of the underlying `indexedDb` and `localStorage` native APIs, and of the lib as the native APIs offer no way to detect changes (so the lib can only detect when something of the lib itself is triggered).

**Comment by michael-lang** [comment]
This could possibly be done with broadcast channel.

https://github.com/pubkey/broadcast-channel
