### ISSUE TITLE
Multiple stores?

### ISSUE THREAD

**Issue by juristr** [cyrilletuzi/angular-async-local-storage#39]
Hi,

might it be possible to have multiple stores? Like I have the scenario where I save flags and settings of the app (which you'd normally put in localStorage). But then I also have some app data which I regularly sync. For that 2nd scenario, I simply do a wipe & resync when I need to refresh the data, but obviously I'd only like to `.clear()` the app data, not the user's settings and flags.  
Ofc, what I could do is to use a single "key" and store an array of app data inside there, but since it's a lot of data (PDF documents in binary form), I wouldn't want to serialize/deserialize it continuously from memory.

With the current implementation this isn't possible I guess, right? Any interest/idea on adding this feature? Would also be willing to help in case.

**Comment by cyrilletuzi** [comment]
Hi @juristr,

I'm not opposed to the feature, how would you design it?

One thing that can be challenging is the feature should be compatible with `IndexedDB` _and_  the `localStorage` fallback.

**Comment by juristr** [comment]
🤔 hmm...true that, didn't think about the `localStorage` fallback. One possibility would be to add the "store name" as a key prefix. But yes...you wouldn't get the same

**Comment by dphochman** [comment]
Hi @juristr & @cyrilletuzi,
It might suffice to removeItem multiple items, passing a prefix, or a pattern, or a list of keys.  That would let us use a prefix as a substitute for a store name.  Is that possible?

**Comment by cyrilletuzi** [comment]
@dphochman Can be done for `getItem`, `setItem` and `clearItem`, but the problem is for `clear` when in `localStorage` fallback scenario.

It would suppose to know all the keys with the wanted prefixed stored in `localStorage`, and I don't know a way to do that.

**Comment by cyrilletuzi** [comment]
I see two options possible if this feature is implemented:
- restrict the API (no `clear` method in that case)
- warn that `clear` will not work in fallback scenarios.

**Comment by cyrilletuzi** [comment]
@dphochman I don't see from where comes `index` in your example.

To be sure we understand each other: when I talked about `localStorage`, it is the native API / variable (`window.localStorage`), not the service provided by the lib.

**Comment by cyrilletuzi** [comment]
@dphochman Damn, I didn't even know the `localStorage.key` method! Seems we have a solution then.

So I'll look into the implementation of this feature.

**Comment by cyrilletuzi** [comment]
@juristr How do you see the API of this feature, regarding to your needs?

**Comment by cyrilletuzi** [comment]
Thoughts for discussion:

Having:
```typescript
.getItem('key', { storageName: 'test' })
.setItem('key', 'value', { storageName: 'test' })
.removeItem('key', { storageName: 'test' })
```
is not of great use. It's a little cleaner, but also more verbose. You could simply do with the current API:
```typescript
.getItem('test_key')
.setItem('test_key', 'value')
.removeItem('test_key')
```

And then we could have this new option just for `clear`:
```typescript
.clear({ startWith: 'test_' })
```

What do you think?

**Comment by dphochman** [comment]
@cyrilletuzi: that solution works for me, and it seems like an understandable way to partition the IndexDB & localStorage. It also seems like a much smaller footprint than what @juristr or i suggested, so it would be easier to test.

**Comment by juristr** [comment]
@cyrilletuzi damn, sorry this discussion got completely lost in my inbox. I'll go through it and provide you some feedback regarding my use case. just give me a couple more days 🙂

**Comment by cyrilletuzi** [comment]
@juristr @dphochman This will be tracked in #54. Please go to this issue and comment with any useful information. Thanks.

**Comment by cyrilletuzi** [comment]
Added in 7.1.0-beta.0. See #54 to track the stable release.
