### ISSUE TITLE
Failed to execute 'transaction' on 'IDBDatabase' on Google Chrome

### ISSUE THREAD

**Issue by nmingaleev** [cyrilletuzi/angular-async-local-storage#40]
Error: Uncaught (in promise): InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    

Occasionally I get this error from the client through sentry and I don't know what the issue might be.
Google Chrome Version 67.0.3396.99

**Comment by cyrilletuzi** [comment]
Please provide a reproduction of the issue, otherwise I can't help.

**Comment by nmingaleev** [comment]
I wish I could :) I thought maybe you have encountered this issue before and know how to fix it :)

**Comment by cyrilletuzi** [comment]
If I had this issue, I would have fixed it already. ;)

Closing this for now then, feel free to comment with a reproduction and I'll reopen it.
