### ISSUE TITLE
Import service that don't need to define in constructors

### ISSUE THREAD

**Issue by 51303014** [cyrilletuzi/angular-async-local-storage#52]
I have an issue when I extends one class and call value in constructors : 
Ex: `
export class TestStore extends CommonStore<TestState> {
  constructor() {
    super('test', init)
  }
}
`
And class CommonStore I want call service localStorage in your library.
`
export abstract class CommonStore<S>
  protected constructor(private key: string, init?: S) {
    super(
     // How to I able to use function localStorage that don't need inject into constructors? 
   // Type of I able to import and call it.
    )
}
`
Please help me .
Thanks

**Comment by cyrilletuzi** [comment]
You can't. Nothing relative to this library in here, it's just how Angular works. Services have to be injected in a constructor that is called at some point, so in non-abstract classes.
