### ISSUE TITLE
Feature Request: support for ng-add

### ISSUE THREAD

**Issue by Sevyls** [cyrilletuzi/angular-async-local-storage#53]
```
 ng add @ngx-pwa/local-storage@7

Installing packages for tooling via npm.
+ @ngx-pwa/local-storage@7.0.0
added 1 package from 1 contributor and audited 40277 packages in 8.423s
found 0 vulnerabilities
```
Installed packages for tooling via npm.
The package that you are trying to add does not support schematics. You can try using a different version of the package or **contact the package author to add ng-add support.**

**Comment by cyrilletuzi** [comment]
@Sevyls What would be the point? To use this lib, you just have to `npm install` it, `ng add` is useful when there are additional setup steps, which is not the case here.

**Comment by cyrilletuzi** [comment]
Closing as there is no answer.

To be clear: I'm not opposed to this feature, but I have currently no time to spend on a feature which adds no actual feature. But feel free to submit a PR.

**Comment by cyrilletuzi** [comment]
For info, this is reintroduced in #170, as there are now additional steps that could be automated.
