### ISSUE TITLE
Version 7.1.0 uses localStorage instead of IndexedDB 

### ISSUE THREAD

**Issue by marcstee** [cyrilletuzi/angular-async-local-storage#57]
After upgrading Angular and this lib to latest version: **7.1.0** (for both) it started to use localStorage instead of IndexedDB which it was using before. I'm using Chrome 70 (70.0.3538.110) and checked it as well on Safar 12.0.1 (14606.2.104.1.1) - both on OSX 10.14.1.

My package.json looks like this:

> {
>   "name": "myrepo",
>   "version": "1.0.0",
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "^7.1.0",
>     "@angular/cdk": "^7.1.0",
>     "@angular/common": "^7.1.0",
>     "@angular/compiler": "^7.1.0",
>     "@angular/core": "^7.1.0",
>     "@angular/forms": "^7.1.0",
>     "@angular/http": "^7.1.0",
>     "@angular/material": "^7.1.0",
>     "@angular/material-moment-adapter": "^7.1.0",
>     "@angular/platform-browser": "^7.1.0",
>     "@angular/platform-browser-dynamic": "^7.1.0",
>     "@angular/pwa": "^0.10.6",
>     "@angular/router": "^7.1.0",
>     "@angular/service-worker": "^7.1.0",
>     "@ngx-pwa/local-storage": "^7.1.0",
>     "core-js": "^2.5.4",
>     "moment": "^2.22.2",
>     "rxjs": "^6.3.3",
>     "zone.js": "~0.8.26"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "^0.10.6",
>     "@angular/cli": "~7.0.6",
>     "@angular/compiler-cli": "^7.1.0",
>     "@angular/language-service": "^7.1.0",
>     "@types/jasmine": "^3.3.0",
>     "@types/jasminewd2": "^2.0.6",
>     "@types/node": "^10.12.10",
>     "codelyzer": "~4.5.0",
>     "jasmine-core": "~3.3.0",
>     "jasmine-spec-reporter": "~4.2.1",
>     "karma": "~3.1.1",
>     "karma-chrome-launcher": "~2.2.0",
>     "karma-coverage-istanbul-reporter": "^2.0.4",
>     "karma-jasmine": "~2.0.1",
>     "karma-jasmine-html-reporter": "^1.4.0",
>     "protractor": "^5.4.1",
>     "ts-node": "~7.0.1",
>     "tslint": "~5.11.0",
>     "typescript": "~3.1.6"
>   }
> }
>

**Comment by cyrilletuzi** [comment]
Woush! This is an unforeseen consequences of this [commit](https://github.com/cyrilletuzi/angular-async-local-storage/commit/1bf2d002a6d3109faf617ac9f6126351083c1c90#diff-e4cd449c2f6d227facbf30b8df326307).

I have released a revert and hot fix in 7.1.1.

But it introduces #58.

@marcstee Thanks for reporting.

**Comment by cyrilletuzi** [comment]
Note: I added a test to prevent this to happen again.

**Comment by cyrilletuzi** [comment]
Another note: 7.1.0 and 7.1.1 has been deprecated in favor of 7.2, which fix all the issues.

See the [changelog](https://github.com/cyrilletuzi/angular-async-local-storage/blob/master/CHANGELOG.md) for details.
