### ISSUE TITLE
I can do the `removeItem` command

### ISSUE THREAD

**Issue by MatheusBarem** [cyrilletuzi/angular-async-local-storage#59]
I need to remove the variable in the indexedDB  but the command `removeItem` doesn't work at all(don't show any errors).

I'm using this command:

`this.storage.removeItem('dateFilter').subscribe(() => {});`

**Comment by cyrilletuzi** [comment]
@MatheusBarem Such main operations are tested before every release, and tests are OK.

You have to provide a reproduction of the issue, otherwise I can't help.

**Comment by cyrilletuzi** [comment]
Closing for house-keeping purpose, as there is no news. I'll reopen the issue if new elements are given.

**Comment by MatheusBarem** [comment]
In my app.components.ts I have a function that needs to `removeItem` when i click in a link, I need to remove the item dateFilter:

**my function in my app.components** 

```
 clearFilter(){   
    this.storage.removeItem('dateFilter').subscribe(() => {});
  }
```
**my app.components.html (where my function is called)**

```
 <li *ngIf="user.storeOwner || menu.includes('report_employees')">
              <a class="sub-links" (click)="sendToPage('/employees-report', langs.reports + ' > ' + langs.professionals); clearFilter()">{{langs.professionals
                || 'Profissionais' }}</a>
 </li>
```
All works fine but don't delete the item when i click and don't show any errors.
