### ISSUE TITLE
i use angular 4.0 typescript 2.2

### ISSUE THREAD

**Issue by grubed** [cyrilletuzi/angular-async-local-storage#6]
ERROR in Error encountered resolving symbol values statically. Calling function
' makeDecorator', function calls are not supported. Consider replacing the funct
ion or lambda with a reference to an exported function, resolving symbol NgModul
e in D:/code/iris_angular_gitlab/node_modules/angular-async-local-storage/node_m
odules/@angular/core/core.d.ts, resolving symbol AsyncLocalStorageModule in D:/c
ode/iris_angular_gitlab/node_modules/angular-async-local-storage/src/async-local
-storage_module.d.ts, resolving symbol AsyncLocalStorageModule in D:/code/iris_a
ngular_gitlab/node_modules/angular-async-local-storage/src/async-local-storage_m
odule.d.ts

**Comment by cyrilletuzi** [comment]
Could you do an example of your code ? I have no problem with Angular 4.0 and TypeScript 2.2, and the error doesn't help to know what's wrong.
