### ISSUE TITLE
Support for "upgradeneeded"

### ISSUE THREAD

**Issue by tluckett77** [cyrilletuzi/angular-async-local-storage#60]
Working on a fairly complex project has presented the challenge of managing database data versions. Has there been given any thought into supporting database version control through the "upgradeneeded" event.  It seems to be in the library, however, used in self management rather than surfacing an interface for application usage. Right now the only option I can see is to manually store and test for versions, which introduces additional challenged around validation and upgrading, or is there a recommendation on how best to deal with data version discrepancies. Thanks.

**Comment by tluckett77** [comment]
This seems to be a viable way of handling version control for data. There may be a considerable stumbling block with one of the main valuable features of the library. The JSON Schema Validation. It would require a growing history of JSON validation Schemas to access all possible versions.

For example: Say person 'A' uses the web application at `version 1` and comes back when `Version 6` is in the wild. First `Version 1` has to be validated as per the required validation, before applying any migration effects. This means every version of the database for the life of the application will grow the the footprint of the application. 1 schema, per field per version.

Thinking it through on the surface, in the spirit of trying to keep things simple would it be helpful to give moderated control back to the developer when it comes to validation in certain circumstances. My Thought is by adding a `currentVersion` in either 

- a public setter to give the option of version control
- a provider property also optional to trigger version control

Say when version control is being used (vis-à-vis **Version Controlled Mode**) , the validation for `getItem` only happens when the the existing version and the `currentVersion` are the same. This would mean only 1 Schema ever needed, the most recent one. Rather than returning a validation error, as currently happens. 

Version Controlled Mode would return a payload rather than the raw data as it does today. For example:
```
interface LocalStorePayload<T> {
  dataVersion: number;
  data: T;
}
```

Now it's possible to retrieve the data, getting around the required validation (the data is stale at this point and shouldn't be used) and can then go through a migration effect. By doing it this way, the need for versioned keys and iterations are no longer needed. 

As for the `localStorage` fallback, I am not exactly sure what to suggest there. I am not fully aware of all the cases in which this can happen outside of old browsers and privacy/incognito modes. Seems like using a version mode should only apply to indexedDB and throw an error on fallback, or console log warning that versioning is being ignored.

**Comment by cyrilletuzi** [comment]
> Version Controlled Mode would return a payload rather than the raw data as it does today

Doesn't seem a good option to me, as the signature of `getItem` is already quite complex/variable because of validation requirements.

Do we agree that migration can only happen when the app starts (and not on punctual calls of `getItem`)? In this case, the lib would just need to provide a method (or else) indicating the version.

An exact explanation of the steps of your migration scenario could help to design this feature correctly.

 > the validation for getItem only happens when the the existing version and the currentVersion are the same. This would mean only 1 Schema ever needed, the most recent one.

Whatever the case, data could have been forged at any time. So validation should happen all the time. But, even if not recommended, bypassing validation is already possible (see [documentation](https://github.com/cyrilletuzi/angular-async-local-storage/blob/master/docs/MIGRATION_TO_V7.md)).

**Comment by cyrilletuzi** [comment]
Ok, thanks for your feedback.

I'll add the investigation for this feature on the roadmap. But don't expect it too soon, it's a busy period for me at work, I'll go into that after holidays.

**Comment by tluckett77** [comment]
Thanks for taking the time to think about this possible enhancement!

**Comment by cyrilletuzi** [comment]
Can you give an example of migration? There's one thing I don't understand: even if you skip validation during migration, you need to know the structure of previous versions to be able to migrate the data, right? So you still need to keep memory of all previous versions, or I am missing something?

**Comment by cyrilletuzi** [comment]
Hi @tluckett77, any news on this?

Current work for v8 may interfere with the feature you asked (as the lib may need to use the `upgradeneeded` event for itself), so I'd be more confident if we think the issue before it's too late.

**Comment by cyrilletuzi** [comment]
Will be possible in v8 via #107 

Documentation will be available in [interoperability guide](https://github.com/cyrilletuzi/angular-async-local-storage/blob/master/docs/INTEROPERABILITY.md) once v8 is released.

Beta documentation can be found in `v8beta` branch.
