### ISSUE TITLE
Validation Documentation notes @ngw-pwa, my code shows @ngx-pwa

### ISSUE THREAD

**Issue by alignsoft** [cyrilletuzi/angular-async-local-storage#61]
In the Validation documentation regarding the use of JSON schema's, all the imports are from '@**ngw**-pwa/local-storage', while my project imports from '@**ngx**-pwa/local-storage', @ngw redlines in VSCode.

Is the documentation incorrect, or do I have an issue with my library?

**Comment by cyrilletuzi** [comment]
It's just a typo I often do. :/ Documentation fixed, thanks for reporting.
