### ISSUE TITLE
Optional properties in an object are still validated

### ISSUE THREAD

**Issue by rfcheung** [cyrilletuzi/angular-async-local-storage#63]
If I try to validate an object like the example in the documentation. I get a JSON invalid error.

```
interface User {
  firstName: string;
  lastName: string;
  age?: number;
}

const schema: JSONSchemaObject = {
  properties: {
    firstName: { type: 'string' } as JSONSchemaString,
    lastName: { type: 'string' } as JSONSchemaString,
    age: { type: 'number' } as JSONSchemaNumeric
  },
  required: ['firstName', 'lastName']
};

const user: User = { firstName: 'Foo', lastName: 'Bar };
this.localStorage.setItem('user', user).subscribe(() => {});

this.localStorage.getItem<User>('user', { schema }).subscribe(res => console.log(res));
```
![image](https://user-images.githubusercontent.com/995636/49881080-c1034300-fe2d-11e8-9dde-82eb6e78ba82.png)

Am I doing something wrong?

Tested with 7.2.0

**Comment by cyrilletuzi** [comment]
This scenario is tested, and the test is OK.

There is a missing `'` after `Bar` in your code, is that normal?
```typescript
const user: User = { firstName: 'Foo', lastName: 'Bar };
```

**Comment by cyrilletuzi** [comment]
Fixed in v5.3.2, v6.2.1 and v7.2.1.

@rfcheung Thanks for reporting. 👍

**Comment by bogacg** [comment]
Is it possible this problem still continues ? (v9-beta1)

**Comment by cyrilletuzi** [comment]
No, it's supposed to be fixed. If you found a bug, please file a new issue with a reproduction.
