### ISSUE TITLE
TypeError: Cannot read property 'objectStoreNames' of undefined

### ISSUE THREAD

**Issue by sebaherrera** [cyrilletuzi/angular-async-local-storage#87]
Hi. I'm getting the following error:

"TypeError: Cannot read property 'objectStoreNames' of undefined"

Browsers: Chrome Mobile Webview 71.0.3578 on Android 6.0.1, Chrome Mobile WebView 72.0.3626 on Android 7, 7.1.1 and 8, Facebook version 196 (Android 6.0.1) and 205 (Android 7).

Stack trace:

File webpack:///./node_modules/@ngx-pwa/local-storage/fesm5/ngx-pwa-local-storage.js.pre-build-optimizer.js line 528 col 27 in t._next
if (!database.objectStoreNames.contains(_this.objectStoreName)) {
File webpack:///./node_modules/rxjs/_esm5/internal/Subscriber.js.pre-build-optimizer.js line 194 col 16 in t.__tryOrUnsub
fn.call(this._context, value);
File webpack:///./node_modules/rxjs/_esm5/internal/Subscriber.js.pre-build-optimizer.js line 132 col 22 in t.next
this.__tryOrUnsub(this._next, value);
File webpack:///./node_modules/rxjs/_esm5/internal/Subscriber.js.pre-build-optimizer.js line 76 col 26 in t._next
this.destination.next(value);
File webpack:///./node_modules/rxjs/_esm5/internal/Subscriber.js.pre-build-optimizer.js line 53 col 18 in t.next
this._next(value);
File webpack:///./node_modules/rxjs/_esm5/internal/operators/tap.js.pre-build-optimizer.js line 51 col 26 in t._next
this.destination.next(value);
File webpack:///./node_modules/rxjs/_esm5/internal/Subscriber.js.pre-build-optimizer.js line 53 col 18 in t.next
this._next(value);
File webpack:///./node_modules/rxjs/_esm5/internal/operators/take.js.pre-build-optimizer.js line 40 col 30 in t._next
this.destination.next(value);
File webpack:///./node_modules/rxjs/_esm5/internal/Subscriber.js.pre-build-optimizer.js line 53 col 18 in t.next
this._next(value);
File webpack:///./node_modules/rxjs/_esm5/internal/observable/fromEvent.js.pre-build-optimizer.js line 18 col 28 in IDBOpenDBRequest.<anonymous>
subscriber.next(Array.prototype.slice.call(arguments));

It may be related to .size property, but I'm not really sure about that.

**Comment by cyrilletuzi** [comment]
Hi @sebaherrera, thanks for your feedback.

To be able to help you, I need:
- the version of Angular you are using
- the version of this lib you are using,
- a minimal reproduction of the code which raises this error.

Also, could you try with v8 beta, as a lot of edgy cases have been fixed? You'll find instructions in #76.

Working now, I'll look into this issue later today.

**Comment by sebaherrera** [comment]
Thanks for your answer. Here is the relevant code:

import { LocalStorage } from '@ngx-pwa/local-storage';
....
  constructor(private router: Router, protected localStorage: LocalStorage, private activatedRoute: ActivatedRoute,
    private appRef: ApplicationRef)
....
  contarItems() {
    this.localStorage.size.subscribe((size) => {
      this.CantidadCarrito = size;
    });
  }

Angular version: 7.2.7
Library version: 7.4.2

I catched this issue via Rollbar. I wasn't able to reproduce myself, since it occurs in a few cases, so it might take a while to check if it is fixed on v8.

**Comment by cyrilletuzi** [comment]
@sebaherrera Thanks for your answer.

Given the error message, if it's only happen sometimes, it's probably happening when the storage is empty. Could you check if you can reproduce the problem if you clear your browser storage?

If so, you could then check with v8 beta.

**Comment by sebaherrera** [comment]
I cleared ObjectStore and full DB but cannot reproduce the issue. I think that there are specific cases where ObjectStore cannot be created, like https://bugzilla.mozilla.org/show_bug.cgi?id=1423917, and that triggers the error.

I'll be in touch when I have more information. Thank you.

**Comment by cyrilletuzi** [comment]
@sebaherrera Were you able to test with v8 beta? Instructions in #76 .

v8 will be a nearly full rewrite of the lib, partly to prevent edgy cases issues. So I would like to be sure your issue is fixed before v8 stable.

**Comment by sebaherrera** [comment]
Hi. I tried it on staging and limited test and works right. But remember: there were some specific cases catched via Rollbar that I couldn't reproduce, so don't take my word as final.

Thanks for your help!

**Comment by cyrilletuzi** [comment]
@sebaherrera Thanks for your feedback. Let me know if there is anything new.

**Comment by cyrilletuzi** [comment]
I'll close this issue for house keeping, as, if it's still there, it's the same as #95.
