### ISSUE TITLE
How to use in testing

### ISSUE THREAD

**Issue by AndrePalantir** [cyrilletuzi/angular-async-local-storage#88]
Hi, I want to create unit tests to assert the creating of the stores in my services. But how can I do it against ChromeHeadless? These tests are going to be in CI so I can't rely on manual testing alone.

**Comment by cyrilletuzi** [comment]
Hi, as the purpose of the lib is to manage such low-level operations, it's also the role of the lib to do this kind of tests. So eitheir you trust the lib (which should be the case if you chose to use it), or you'll have to do manual `indexedDB` tests. Feel free to get inspiration from the tests on this repo, but I can't help you more on this.
