### ISSUE TITLE
not working with universal

### ISSUE THREAD

**Issue by Gorniv** [cyrilletuzi/angular-async-local-storage#9]
I dont can run universal app with 'ts-node' and 'angular-async-local-storage'
source app: https://github.com/gorniv/universal/tree/material
```
/Users/Gorniv/GitHub/universal/UniApp/node_modules/angular-async-local-storage/src/async-local-storage.js:1
(function (exports, require, module, __filename, __dirname) { import { Injectable } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.angular-async-local-storage/src/async-local-storage (/Users/Gorniv/GitHub/universal/UniApp/dist-server/main.462f910c364768b8c046.bundle.js:4079:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! universal-demo@0.0.0 uad: `ng build --dev --output-hashing=all --aot=true && ng build --aot=true --output-hashing=all --dev --app 1 && ts-node server`
```

**Comment by cyrilletuzi** [comment]
It's a known issue for all third party librairies : angular/angular-cli#7200

Currently, to work with Universal via the CLI, even if they are Universal-compatible, librairies have to be packaged in a very specific way, and the Angular team hasn't published clear instructions about this yet.

The CLI should solve this issue in next releases.

**Comment by Gorniv** [comment]
thank you!

**Comment by glebmachine** [comment]
@cyrilletuzi how long it will be take?

**Comment by cyrilletuzi** [comment]
No idea, I'm not part of the Angular team and unfortunately they are not very verbose about their work and plans.

But I may solve it by myself for this library in the next days, as I need it in another project.

**Comment by glebmachine** [comment]
Thank you!)

**Comment by cyrilletuzi** [comment]
Solution found, but I will only be able to fix this lib in 2 weeks.

**Comment by cyrilletuzi** [comment]
Fixed in last version.
