### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by spolischook** [cyrilletuzi/angular-async-local-storage#90]
Sorry for silly question in advance...
Have angular ~7.2.0 and @ngx-pwa/local-storage ^6.2.3
Try to simplify my effort as simple as possible:
```ts
import {LocalStorage} from '@ngx-pwa/local-storage';
@Component({})
export class MyComponent implements OnInit {
  ngOnInit() {
    this.localStorage.setItem('foo', 'bar').subscribe(() => {
      this.localStorage.getItem('foo').subscribe(data => {
        console.log(data);
      });
    });
  }
}
```
and it's not work as expected, just log `null`.

**Comment by cyrilletuzi** [comment]
Thanks for your interest for this lib. Your example is the most basic operation possible in this lib, so it would have been caught by tests if it was just that.

So the issue must be somewhere else and I'll need a reproduction of the issue to be able to help you.

**Comment by spolischook** [comment]
Available to reproduce it in fresh instalation - https://github.com/spolischook/test-ng-storage
![Selection_374](https://user-images.githubusercontent.com/1978331/54410577-b8542e80-46f4-11e9-930c-61bcde62f26c.png)

**Comment by cyrilletuzi** [comment]
Thanks for the reproduction.

I've tested it in Chrome too and it works. What is your exact version of Chrome?

**Comment by spolischook** [comment]
```bash
chromium-browser --version
Chromium 71.0.3578.98 Built on Ubuntu , running on Ubuntu 18.04
```

**Comment by cyrilletuzi** [comment]
That's weird. Can you check (in this order):
1. if there is something in the classic "Local Storage"
2. is there a newer version of Chromium available on your OS? if so, could you test with it?
3. could you do a test with all your Chromium extensions disabled?
4. if it's still not OK, could you test with Chromium settings reset?

**Comment by spolischook** [comment]
Confirm weirdness of this issue. 
For now I've able to make it works on incognito mode. Even, after disable all extension it's not works on standard mode. 
![Selection_376](https://user-images.githubusercontent.com/1978331/54429842-4f87a900-472a-11e9-8a23-5ea8437d0862.png)

**Comment by cyrilletuzi** [comment]
That's a start to isolate the issue. If it's working in private mode, I think the most probable options are:
- issue with `indexedDB`: could you check, in both modes (private and non private), both what's in `indexedDB` *and* classic `localStorage`?
- a specific setting of your chromium which get disabled when in private mode.

Another check to try to find the issue: can you test with v8 beta? Instructions in #76

**Comment by cyrilletuzi** [comment]
@spolischook Were you able to test with v8 beta?

v8 will be a nearly full rewrite of the lib, partly to prevent edgy cases issues. So I would like to be sure your issue is fixed before v8 stable.

**Comment by spolischook** [comment]
thanks for your care, I'll test it today!

**Comment by cyrilletuzi** [comment]
@spolischook Have you been able to do the requested tests?

**Comment by cyrilletuzi** [comment]
As there is no news, I'll close this issue for house-keeping purpose. Feel free to comment and I will reopen the issue.
