### ISSUE TITLE
Validate Map object in v6 

### ISSUE THREAD

**Issue by thegeett** [cyrilletuzi/angular-async-local-storage#91]
Not sure how to validate new Map() object, in your Validation Guide you have demonstrate boolean, string, number, array but not map. 
If I have 

let map = new Map();
map.set('abc', someArrayObject);
map.set('def', someArrayObject);

this.localStorage.setItem('test', map).subscribe(() => {
            console.log('Done MAP');
 }, () => {
            console.log('Error MAP');
});

SO how could I create schema to validate map object while getItem()?

**Comment by cyrilletuzi** [comment]
Thanks for your interest for this lib.

Validating a `Map` won't happen at all, as a JavaScript `Map` is not serializable to JSON. To be exact, seriazalization works (`JSON.stringify()`), but when unserializing (`JSON.parse()`), you won't get a real `Map`, just a (useless) object.

To store a `Map`, you need to do this:

```typescript
const index = 'map';
const someMap: Map<string, number> = new Map([['test1', 1], ['test2', 2]]);

/* Writing */
this.localStorage.setItem(index, Array.from(someMap)).subscribe();

/* Reading */
this.localStorage.getItem(index).pipe(
  map((data) => new Map(data)),
).subscribe((data) => {
  data.get('test1');
});
```

Then, to validate, you need to do this:

```typescript
const schema: JSONSchema = {
  type: 'array',
  items: {
    type: 'array',
    items: [
      { type: 'string' },
      { type: 'number' },
    ],
  },
};

this.localStorage.getItem(index, { schema }).pipe(
  map((data) => new Map(data)),
).subscribe((data) => {
  data.get('test1');
});
```

I'll add this in v8 documentation, thanks for pointing this out.

**Comment by cyrilletuzi** [comment]
Edited my answer as it was inexact.

**Comment by thegeett** [comment]
Thanks it worked!
